CREATE TABLE tipo(
	idTipo INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    descTipo VARCHAR(50) NOT NULL,
    obsTipo VARCHAR(150) NOT NULL
);

CREATE TABLE usuario(
	idUser INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    nomeUser VARCHAR(50) NOT NULL,
    emailUser VARCHAR(50) UNIQUE KEY NOT NULL,
    senhaUser VARCHAR(250) NOT NULL,
    idTipo INT NOT NULL, 
    CONSTRAINT fk_usuario_tipo FOREIGN KEY (idTipo) REFERENCES tipo(idTipo)
);